version: "3.1"
services:
    docker-host:
        image: qoomon/docker-host
        cap_add: ["NET_ADMIN", "NET_RAW"]
        restart: unless-stopped
        networks:
            - default
            - project
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./backend:/var/www/html/
        depends_on:
            - php-fpm
        networks:
            - default
            - project
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=project-back.test.ru
            - LETSENCRYPT_HOST=project-back.test.ru
            - LETSENCRYPT_EMAIL=ijakparov@gmail.com
    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./backend:/var/www/html/
        restart: unless-stopped
        expose:
            - "9000"
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

    mysql:
        image: yobasystems/alpine-mariadb
        container_name: project-mysql
        volumes:
            - mysql-project:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123123"
            - "MYSQL_USER=user_x"
            - "MYSQL_PASSWORD=123123"
            - "MYSQL_DATABASE=data_b"
        command: --innodb_use_native_aio=0 --innodb_read_io_threads=64 --innodb_write_io_threads=64 --innodb_io_capacity=5000  --innodb_buffer_pool_size=4G --innodb_log_buffer_size=1G --innodb_log_file_size=1G --query_cache_size=0 --innodb_buffer_pool_dump_at_shutdown=1 --innodb_buffer_pool_load_at_startup=1 --innodb_purge_threads=4 --innodb_flush_log_at_trx_commit=0
        restart: unless-stopped
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - "PMA_HOST=mysql"
            - "PMA_PORT:3306"
            - "VIRTUAL_HOST=project-pma.test.ru"
        restart: unless-stopped
        networks:
            - default
            - project
    node:
        image: node:12.19.0-alpine
        container_name: project-node
        command: npm run dev
        environment:
            - VIRTUAL_HOST=project-front.test.ru
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=project-front.test.ru
            - LETSENCRYPT_EMAIL=test@gmail.com
        volumes:
            - ./frontend/:/var/www
        working_dir: /var/www
        tty: true
        expose:
            - "3000"
        restart: unless-stopped
        networks:
            - default
            - project
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
        container_name: project-elasticsearch
        environment:
            ES_JAVA_OPTS: "-Xms750m -Xmx750m"
        volumes:
            - esdata1:/usr/share/elasticsearch/data
            - "./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:cached"
        expose:
            - "9200"
        restart: unless-stopped
        networks:
            - default
            - vodopad
networks:
    project:
        external: true
volumes:
    mysql-project:
        external: true
